const assert=require('node:assert/strict');const {test}=require('node:test');const {reconcile,parseCSV,reportCSV}=require('./engine.cjs');
const UH='event_id,customer_id,meter,period,currency,quantity\n',PH='customer_id,meter,currency,unit_price,included_units\n',IH='invoice_line_id,customer_id,meter,period,currency,amount\n';
function run(u,p,i=''){return reconcile({usage:UH+u,pricing:PH+p,invoices:IH+i});}
test('finds exact missing invoice without netting overcharges',()=>{const r=run('u1,A,tokens,2026-08,USD,1000\nu2,B,tokens,2026-08,USD,1000','*,tokens,USD,0.01,0','i1,B,tokens,2026-08,USD,15.00');assert.equal(r.totals[0].potential_underbilling,'10.00');assert.equal(r.totals[0].potential_overbilling,'5.00');});
test('uses decimal arithmetic and rounds half up once per month and meter',()=>{const r=run('u1,A,tokens,2026-08,USD,1000000','*,tokens,USD,0.000000005,0');assert.equal(r.results[0].expected,'0.01');});
test('applies included units once and customer rate overrides wildcard',()=>{const r=run('u1,A,tokens,2026-08,USD,60\nu2,A,tokens,2026-08,USD,60','*,tokens,USD,3,0\nA,tokens,USD,2,100');assert.equal(r.results[0].expected,'40.00');});
test('keeps months and currencies separate',()=>{const r=run('u1,A,t,2026-08,USD,1\nu2,A,t,2026-09,USD,1\nu3,A,t,2026-08,NZD,1','*,t,USD,10,0\n*,t,NZD,20,0');assert.equal(r.results.length,3);assert.equal(r.totals.length,2);});
test('does not monetise missing rates or unmatched invoices',()=>{const r=run('u1,A,t,2026-08,USD,1','*,other,USD,1,0','i1,B,t,2026-08,USD,100');assert.equal(r.totals.length,0);assert.equal(r.unresolved,2);});
test('deduplicates identical IDs and rejects conflicting duplicates',()=>{const r=run('u1,A,t,2026-08,USD,10\nu1,A,t,2026-08,USD,10','*,t,USD,1,0','i1,A,t,2026-08,USD,3\ni1,A,t,2026-08,USD,3');assert.equal(r.totals[0].potential_underbilling,'7.00');assert.equal(r.counts.duplicateUsage,1);assert.equal(r.counts.duplicateInvoices,1);assert.throws(()=>run('u1,A,t,2026-08,USD,1\nu1,A,t,2026-08,USD,2','*,t,USD,1,0'),/conflicting/);});
test('includes negative net invoice credits and all invoice lines',()=>{const r=run('u1,A,t,2026-08,USD,10','*,t,USD,1,0','i1,A,t,2026-08,USD,10\ni2,A,t,2026-08,USD,-2');assert.equal(r.results[0].invoiced,'8.00');});
test('parses BOM, quoted delimiters, escaped quotes and CRLF',()=>{assert.deepEqual(parseCSV('\ufeffa,b\r\n"x,y","a""b"\r\n').rows,[{a:'x,y',b:'a"b'}]);assert.equal(parseCSV('a,b\n"one\ntwo",2').rows[0].a,'one\ntwo');});
test('rejects malformed CSV, duplicate headers, bad numbers and unsupported currency',()=>{assert.throws(()=>parseCSV('a,a\n1,2'),/unique/);assert.throws(()=>parseCSV('a,b\n"x,2'),/not closed/);assert.throws(()=>run('u1,A,t,2026-08,USD,-1','*,t,USD,1,0'),/non-negative/);assert.throws(()=>run('u1,A,t,2026-08,JPY,1','*,t,JPY,1,0'),/not supported/);assert.throws(()=>run('u1,A,t,2026-08,USD,1','*,t,USD,1,0','i1,A,t,2026-08,USD,1.001'),/decimal/);});
test('protects CSV export from spreadsheet formulas',()=>{const r=run('u1,=DANGER,t,2026-08,USD,1','*,t,USD,1,0');assert.match(reportCSV(r),/"'=DANGER"/);});
test('missing mandatory column fails clearly',()=>assert.throws(()=>reconcile({usage:'id\na',pricing:PH,invoices:IH}),/missing column event_id/));
