'use strict';
const inputFiles={usage:null,pricing:null,invoices:null};let currentReport=null,isExample=false;
const samples={usage:'event_id,customer_id,meter,period,currency,quantity\nu-001,acme,input_tokens,2026-08,USD,1000000\nu-002,acme,voice_minutes,2026-08,USD,120\nu-003,northstar,input_tokens,2026-08,USD,2000000\nu-004,orbit,voice_minutes,2026-08,USD,90\nu-005,acme,new_meter,2026-08,USD,10\nu-006,southco,voice_minutes,2026-08,NZD,50\nu-006,southco,voice_minutes,2026-08,NZD,50\n',pricing:'customer_id,meter,currency,unit_price,included_units\n*,input_tokens,USD,0.000002,0\n*,voice_minutes,USD,0.15,20\n*,voice_minutes,NZD,0.20,0\n',invoices:'invoice_line_id,customer_id,meter,period,currency,amount\nil-001,acme,input_tokens,2026-08,USD,1.50\nil-002,acme,voice_minutes,2026-08,USD,15.00\nil-003,orbit,voice_minutes,2026-08,USD,14.00\nil-004,unmapped,voice_minutes,2026-08,USD,6.00\n'};
const $=id=>document.getElementById(id);const escapeHTML=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const format=s=>s===null?'—':String(s).replace(/\B(?=(\d{3})+(?!\d))/g,',');
function error(message){$('error').textContent=message;$('error').hidden=!message;}
function resetReport(){currentReport=null;$('report').hidden=true;$('empty').hidden=false;$('totals').replaceChildren();$('rows').replaceChildren();$('export').disabled=true;$('print').disabled=true;$('result-label').textContent='Ready when you are';error('');}
for(const type of Object.keys(inputFiles)){$(type).addEventListener('change',()=>{inputFiles[type]=$(type).files[0]||null;isExample=false;$('ack').checked=false;resetReport();$(type+'-name').textContent=inputFiles[type]?inputFiles[type].name:'No file selected';$('load-status').textContent='';});}
function download(name,text,type='text/csv;charset=utf-8'){const blob=new Blob([text],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function render(report){
 currentReport=report;$('empty').hidden=true;$('report').hidden=false;$('export').disabled=false;$('print').disabled=false;$('result-label').textContent=isExample?'Example data · not customer results':'Your supplied data · review candidates';
 $('quality').textContent=report.counts.usageRows.toLocaleString()+' usage rows · '+report.counts.invoiceRows.toLocaleString()+' invoice rows · '+(report.counts.duplicateUsage+report.counts.duplicateInvoices)+' exact duplicate rows excluded · '+report.unresolved+' unresolved groups excluded from monetary totals.';
 $('totals').innerHTML=report.totals.length?report.totals.map(t=>'<div class="currency"><div class="code">'+escapeHTML(t.currency)+'</div><div class="big">'+format(t.potential_underbilling)+'</div><div class="small">Potential underbilling to review</div><div class="secondarytotal"><span>Potential overbilling</span><strong>'+format(t.potential_overbilling)+'</strong></div><div class="small" style="margin-top:8px">'+t.priced_groups+' priced groups · currencies kept separate</div></div>').join(''):'<div class="notice">No priced usage groups could be compared. Resolve the missing pricing or matching data shown below.</div>';
 const labels={matched:['Matched',''],potential_underbilling:['Potential underbilling','warn'],potential_overbilling:['Potential overbilling','over'],unpriced:['Missing pricing','review'],needs_review:['Missing usage','review']};
 $('rows').innerHTML=report.results.slice(0,500).map(r=>'<tr><td>'+escapeHTML(r.customer_id)+'<span class="sub">'+escapeHTML(r.meter)+' · '+escapeHTML(r.quantity)+' units</span></td><td>'+r.period+'</td><td>'+r.currency+'</td><td class="num">'+format(r.expected)+'</td><td class="num">'+format(r.invoiced)+'</td><td class="num">'+format(r.difference)+'</td><td><span class="badge '+labels[r.status][1]+'">'+labels[r.status][0]+'</span><span class="sub">'+escapeHTML(r.reason)+'</span></td></tr>').join('');
 $('table-caption').textContent=report.results.length+' customer / meter / month / currency groups'+(report.results.length>500?' · first 500 shown; CSV export contains all groups':'');
 $('report-note').textContent='Generated '+new Date().toLocaleString()+' · Klein Billing Check '+report.version+(isExample?' · Illustrative example only':'')+'. Positive differences mean calculated charges exceed supplied invoice lines. Negative differences indicate the reverse.';
 $('load-status').textContent='Comparison complete.';
}
$('sample').addEventListener('click',()=>{resetReport();isExample=true;for(const k of Object.keys(inputFiles)){inputFiles[k]=null;$(k).value='';$(k+'-name').textContent='Using illustrative '+k+' data';}$('ack').checked=true;try{render(KleinBilling.reconcile(samples));}catch(e){error(e.message);}});
$('run').addEventListener('click',async()=>{resetReport();if(!$('ack').checked){error('Confirm that the files cover the same period and match the supported pricing assumptions.');return;}if(isExample){render(KleinBilling.reconcile(samples));return;}if(Object.values(inputFiles).some(f=>!f)){error('Select usage, pricing and invoice CSV files. Use a header-only invoice CSV if nothing was invoiced.');return;}if(Object.values(inputFiles).some(f=>f.size>6000000)){error('Each CSV must be 6 MB or smaller.');return;}$('run').disabled=true;$('load-status').textContent='Reading your files locally…';try{const data={};for(const k of Object.keys(inputFiles))data[k]=await inputFiles[k].text();render(KleinBilling.reconcile(data));}catch(e){error(e.message);$('load-status').textContent='Please correct the input and try again.';}finally{$('run').disabled=false;}});
$('clear').addEventListener('click',()=>{for(const k of Object.keys(inputFiles)){inputFiles[k]=null;$(k).value='';$(k+'-name').textContent='No file selected';}$('ack').checked=false;isExample=false;resetReport();$('load-status').textContent='Files and results cleared from this page.';});
$('export').addEventListener('click',()=>{if(currentReport)download('klein-billing-findings'+(isExample?'-example':'')+'.csv',KleinBilling.reportCSV(currentReport));});$('print').addEventListener('click',()=>{if(currentReport)window.print();});
for(const b of document.querySelectorAll('[data-template]'))b.addEventListener('click',()=>download('klein-'+b.dataset.template+'-example.csv',samples[b.dataset.template]));
const checkoutURL='https://buy.stripe.com/14A8wP4SMgsf4ZPbyN0sU04';if(checkoutURL.startsWith('https://buy.stripe.com/')){$('checkout').href=checkoutURL;$('checkout').target='_blank';$('checkout').rel='noopener noreferrer';$('checkout').textContent='Buy business licence — US$49';}
